import "/style.css";
import imgLogo from "../public/logo4d.svg";
import imgVideoGameLight from "../public/img-videogame-light.svg";
import imgVideoGameDark from "../public/img-videogame-dark.svg";
import imgDevelopmentLight from "../public/img-development-light.svg";
import imgDevelopmentDark from "../public/img-development-dark.svg";
import carlos from "../public/carlos.svg";
import davi from "../public/davi.svg";
import bruno from "../public/bruno.svg";
import leo from "../public/leo.svg";
import jhonata from "../public/jhonata.svg";
import pedro from "../public/pedro.svg";

document.getElementById("image-logo").src = imgLogo;
document.getElementById("img-videogame-light").src = imgVideoGameLight;
document.getElementById("img-videogame-dark").src = imgVideoGameDark;
document.getElementById("img-development-light").src = imgDevelopmentLight;
document.getElementById("img-development-dark").src = imgDevelopmentDark;
document.getElementById("img-carlos").src = carlos;
document.getElementById("img-davi").src = davi;
document.getElementById("img-bruno").src = bruno;
document.getElementById("img-leo").src = leo;
document.getElementById("img-jhonata").src = jhonata;
document.getElementById("img-pedro").src = pedro;
